create table "public"."package_user" (
    "id" bigint generated always as identity not null,
    "user_id" uuid not null,
    "package_id" bigint not null,
    "created_at" timestamp with time zone default now()
);


create table "public"."packages" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "scope" text
);


alter table "public"."packages" enable row level security;

CREATE UNIQUE INDEX package_user_pkey ON public.package_user USING btree (id, user_id, package_id);

CREATE UNIQUE INDEX packages_pkey ON public.packages USING btree (id);

CREATE UNIQUE INDEX users_pkey ON public.users USING btree (id);

alter table "public"."package_user" add constraint "package_user_pkey" PRIMARY KEY using index "package_user_pkey";

alter table "public"."packages" add constraint "packages_pkey" PRIMARY KEY using index "packages_pkey";

alter table "public"."users" add constraint "users_pkey" PRIMARY KEY using index "users_pkey";

alter table "public"."package_user" add constraint "package_user_package_id_fkey" FOREIGN KEY (package_id) REFERENCES packages(id) not valid;

alter table "public"."package_user" validate constraint "package_user_package_id_fkey";

alter table "public"."package_user" add constraint "package_user_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) not valid;

alter table "public"."package_user" validate constraint "package_user_user_id_fkey";

grant delete on table "public"."package_user" to "anon";

grant insert on table "public"."package_user" to "anon";

grant references on table "public"."package_user" to "anon";

grant select on table "public"."package_user" to "anon";

grant trigger on table "public"."package_user" to "anon";

grant truncate on table "public"."package_user" to "anon";

grant update on table "public"."package_user" to "anon";

grant delete on table "public"."package_user" to "authenticated";

grant insert on table "public"."package_user" to "authenticated";

grant references on table "public"."package_user" to "authenticated";

grant select on table "public"."package_user" to "authenticated";

grant trigger on table "public"."package_user" to "authenticated";

grant truncate on table "public"."package_user" to "authenticated";

grant update on table "public"."package_user" to "authenticated";

grant delete on table "public"."package_user" to "service_role";

grant insert on table "public"."package_user" to "service_role";

grant references on table "public"."package_user" to "service_role";

grant select on table "public"."package_user" to "service_role";

grant trigger on table "public"."package_user" to "service_role";

grant truncate on table "public"."package_user" to "service_role";

grant update on table "public"."package_user" to "service_role";

grant delete on table "public"."packages" to "anon";

grant insert on table "public"."packages" to "anon";

grant references on table "public"."packages" to "anon";

grant select on table "public"."packages" to "anon";

grant trigger on table "public"."packages" to "anon";

grant truncate on table "public"."packages" to "anon";

grant update on table "public"."packages" to "anon";

grant delete on table "public"."packages" to "authenticated";

grant insert on table "public"."packages" to "authenticated";

grant references on table "public"."packages" to "authenticated";

grant select on table "public"."packages" to "authenticated";

grant trigger on table "public"."packages" to "authenticated";

grant truncate on table "public"."packages" to "authenticated";

grant update on table "public"."packages" to "authenticated";

grant delete on table "public"."packages" to "service_role";

grant insert on table "public"."packages" to "service_role";

grant references on table "public"."packages" to "service_role";

grant select on table "public"."packages" to "service_role";

grant trigger on table "public"."packages" to "service_role";

grant truncate on table "public"."packages" to "service_role";

grant update on table "public"."packages" to "service_role";


