alter table "public"."package_user" drop constraint if exists "package_user_package_id_fkey";

alter table "public"."package_user" drop constraint if exists "package_user_user_id_fkey";

create table "public"."changelogs" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "package_id" bigint not null,
    "changelog" text not null
);


alter table "public"."changelogs" enable row level security;

create table "public"."releases" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "package_id" bigint not null,
    "version" text not null,
    "release_notes" text not null,
    "published_at" timestamp with time zone default now()
);


alter table "public"."releases" enable row level security;

alter table "public"."package_user" alter column "id" set generated by default;

alter table "public"."packages" add column "repository" text not null;

CREATE UNIQUE INDEX changelogs_pkey ON public.changelogs USING btree (id);

CREATE UNIQUE INDEX releases_pkey ON public.releases USING btree (id);

CREATE UNIQUE INDEX releases_version_key ON public.releases USING btree (version);

alter table "public"."changelogs" add constraint "changelogs_pkey" PRIMARY KEY using index "changelogs_pkey";

alter table "public"."releases" add constraint "releases_pkey" PRIMARY KEY using index "releases_pkey";

alter table "public"."changelogs" add constraint "changelogs_package_id_fkey" FOREIGN KEY (package_id) REFERENCES packages(id) ON DELETE CASCADE not valid;

alter table "public"."changelogs" validate constraint "changelogs_package_id_fkey";

alter table "public"."releases" add constraint "releases_package_id_fkey" FOREIGN KEY (package_id) REFERENCES packages(id) ON DELETE CASCADE not valid;

alter table "public"."releases" validate constraint "releases_package_id_fkey";

alter table "public"."releases" add constraint "releases_version_key" UNIQUE using index "releases_version_key";

alter table "public"."package_user" add constraint "package_user_package_id_fkey" FOREIGN KEY (package_id) REFERENCES packages(id) ON DELETE CASCADE not valid;

alter table "public"."package_user" validate constraint "package_user_package_id_fkey";

alter table "public"."package_user" add constraint "package_user_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE not valid;

alter table "public"."package_user" validate constraint "package_user_user_id_fkey";

grant delete on table "public"."changelogs" to "anon";

grant insert on table "public"."changelogs" to "anon";

grant references on table "public"."changelogs" to "anon";

grant select on table "public"."changelogs" to "anon";

grant trigger on table "public"."changelogs" to "anon";

grant truncate on table "public"."changelogs" to "anon";

grant update on table "public"."changelogs" to "anon";

grant delete on table "public"."changelogs" to "authenticated";

grant insert on table "public"."changelogs" to "authenticated";

grant references on table "public"."changelogs" to "authenticated";

grant select on table "public"."changelogs" to "authenticated";

grant trigger on table "public"."changelogs" to "authenticated";

grant truncate on table "public"."changelogs" to "authenticated";

grant update on table "public"."changelogs" to "authenticated";

grant delete on table "public"."changelogs" to "service_role";

grant insert on table "public"."changelogs" to "service_role";

grant references on table "public"."changelogs" to "service_role";

grant select on table "public"."changelogs" to "service_role";

grant trigger on table "public"."changelogs" to "service_role";

grant truncate on table "public"."changelogs" to "service_role";

grant update on table "public"."changelogs" to "service_role";

grant delete on table "public"."releases" to "anon";

grant insert on table "public"."releases" to "anon";

grant references on table "public"."releases" to "anon";

grant select on table "public"."releases" to "anon";

grant trigger on table "public"."releases" to "anon";

grant truncate on table "public"."releases" to "anon";

grant update on table "public"."releases" to "anon";

grant delete on table "public"."releases" to "authenticated";

grant insert on table "public"."releases" to "authenticated";

grant references on table "public"."releases" to "authenticated";

grant select on table "public"."releases" to "authenticated";

grant trigger on table "public"."releases" to "authenticated";

grant truncate on table "public"."releases" to "authenticated";

grant update on table "public"."releases" to "authenticated";

grant delete on table "public"."releases" to "service_role";

grant insert on table "public"."releases" to "service_role";

grant references on table "public"."releases" to "service_role";

grant select on table "public"."releases" to "service_role";

grant trigger on table "public"."releases" to "service_role";

grant truncate on table "public"."releases" to "service_role";

grant update on table "public"."releases" to "service_role";


